### ISSUE TITLE
ddrescue / clonezilla

### ISSUE THREAD

**Issue by Pommesumdreher** [rescatux/rescatux#92]
Maybe you can integrate the "gddrescue"-Package into the Live-System. It is useful to rescue data from a damaged hard drive or disk...
Currently you have to install it every time manually (with the need of an internet-connection).

or maybe clonezilla?

**Comment by adrian15** [comment]
Well, the main purpose of Rescatux is to rescue your system. By that I mean to rescue the ability to be able to gain control of. Either you can login again because you could reset your password or you can boot again into it because Grub or UEFI have been fixed.

I think I installed photorec and testdisk because someone asked it. I might end adding also gddrescue if it's an standard Debian jessie package.

I once took a quick look at clonezilla (its main program actually) and it's not easy to implement it.

Anyways as a second big step for Rescatux I wanted to add some options for migrating systems (from System A to System B). So that might fit into it.

gddrescue and myrescue seem quite small sized. I won't give support for them though.
