### ISSUE TITLE
Can't boot Rescatux in UEFI mode on Asus M5A97 R2.0

### ISSUE THREAD

**Issue by frontierpsycho** [rescatux/rescatux#96]
I tried booting into Rescatux 0.51b3 in UEFI mode. Rescatux booted, but in legacy BIOS mode instead. I can provide more information if requested.

**Comment by frontierpsycho** [comment]
It was just Secure Boot preventing it. I deactivated it and it worked.

**Comment by adrian15** [comment]
Feel free to test Rescatux 0.71-beta7 which now supports booting from Secure Boot enabled UEFI.
Please make issue a new bug with your results (either good or bad) if you ever do it.

Thank you very much!

**Comment by Merdead** [comment]
Hi Adrian,
I have the same problem since I just flashed my Bios as I had lots of failed starts today. The PC is booting now fine and constantly, but Rescatux (downloaded yesterday, so it's the latest version) is still booting in secure mode only.
I wrote this afternoon on the Chat of Rescatux, but got no answer. Are the log files saved on the USB Stick, so I could pass them on to you another way?

**Comment by Merdead** [comment]
I got Mint running again, still it seems the partitions of Win and Mint have different partition systems. (MBR and EFI?) Could that be the reason why my Win is not shown in the boot menu? If so, I'd need a very detailed description how to fix that please.
